chore: bump nexus version to 2.12.1
sirclo-solution/template-urban pull request #26
Opened 2022-06-13 05:00 UTC by falmesino

URL PR: https://github.com/sirclo-solution/template-urban/pull/26
URL Task: https://phabricator.sirclo.com/T32880
Pull Latest: OK
Build (Local): OK

<img width="1680" alt="Screen Shot 2022-06-13 at 12 00 20" src="https://user-images.githubusercontent.com/1308515/173283166-37c4a2c3-b5a2-45b6-8aac-3cf760f46f4f.png">

***
Permintaan @inezamandha untuk mengecek tampilan membership level, group dan null ternyata benar belum ke-styling.

Untuk yang disclaimer message di cart dan place-order tidak muncul, musti nanya duls.

**Mobile**

![Screen Shot 2022-06-14 at 16 37 41](https://user-images.githubusercontent.com/1308515/173552276-01b3139b-a6e7-4496-906b-afa40a8019f6.png)

![Screen Shot 2022-06-14 at 16 35 59](https://user-images.githubusercontent.com/1308515/173552291-52d124e5-8d0c-48d2-8f81-6cb06b827651.png)

![Screen Shot 2022-06-14 at 17 35 41](https://user-images.githubusercontent.com/1308515/173558116-88857f8e-942b-4d70-bc09-37e37aa09de6.png)

**Desktop**

![Screen Shot 2022-06-14 at 16 35 53](https://user-images.githubusercontent.com/1308515/173552298-8d0e4a3e-feba-4c75-8a79-72857f4a17dd.png)

![Screen Shot 2022-06-14 at 15 53 54](https://user-images.githubusercontent.com/1308515/173552299-beaa56fe-feb3-4beb-b234-75498a0c1953.png)

![Screen Shot 2022-06-14 at 17 35 37](https://user-images.githubusercontent.com/1308515/173558144-710e47e6-74bf-4938-8749-f1c7748a93c5.png)

***
Tambahan
Menghilangkan inputan arrow bawaan di input type number cart detail

**Sebelum**
![Screen Shot 2022-06-14 at 17 04 39](https://user-images.githubusercontent.com/1308515/173552465-241f4810-4f12-4520-b8b9-fd00dd4eddbb.png)

**Sesudah**
![Screen Shot 2022-06-14 at 17 04 31](https://user-images.githubusercontent.com/1308515/173552444-a6d804b0-fbaf-49e5-9486-492b7953a733.png)

2022-06-13 05:35 UTC, tiarss approved these changes

2022-06-13 05:56 UTC, inezamandha approved these changes

2022-06-13 06:31 UTC, Sukmaarifin approved these changes

2022-06-14 02:15 UTC, inezamandha commented
aku request changes dulu ya jadinya, tapi ini pertanyaan 😹 

1. mau nanya, ini boleh tolong dicek enggak ya mang **di bagian membership (casenya kalau membership null)**, masih muncul bullet pointsnya atau engga? (ini kejadiannya pas naik di 2.11.4, seingetku urban kemarin aku belum megang fixing stylingnya)

kalau ada bullet points mungkin bisa dihilangkeun ya bisa merujuk ke template lain yang udah (i.e. bambita). soalnya designer bilang tidak ada bullet points

2. di urban sudah ada **disclaimer message** belum ya mang? kalau udah ada, seingetku di 2.12.0 (refer to template merlin) udah support nexusnya untuk disclaimer message di cart & placeorder (jadi ketampil tulisannya, sebelumnya belum ada). tapi jadi berantakan tampilannya. tanya ke desainer di `display: none` in dulu kebetulan belum ada desainnya (yang merlin)

2022-06-14 02:19 UTC, inezamandha requested changes
request changesnya merujuk ke pertanyaan di komen hehehe. kalau sudah ada konpirmasi tak approve~

2022-06-14 10:44 UTC, inezamandha requested changes

2022-06-14 10:44 UTC, inezamandha commented on locales/id/membership.ts
> +    "youHave": "Anda Memiliki",
ini apa pakai "Anda memiliki" mang? case sensitive ya 😂 kayaknya template lain seperti itu

2022-06-14 10:44 UTC, inezamandha commented on locales/en/membership.ts
> +    "youHave": "You Have",
ini sama seperti yang "Anda memiliki"

2022-06-15 05:03 UTC, inezamandha approved these changes

2022-06-15 06:40 UTC, merged