fix: bump nexus 2.13.1
sirclo-solution/template-urban pull request #38
Opened 2022-07-28 09:11 UTC by DiebrataA

Summary:
- Add loader component, bank logos on coupon
- Add moreShipping ClassName in shipping_method page
- Change Google SSO butto
![coupon_payment](https://user-images.githubusercontent.com/38358288/181468324-1fce78b0-274f-4002-860c-15c38303417c.png)
![coupon_place-order](https://user-images.githubusercontent.com/38358288/181468335-6cca074f-17b5-49d6-a30d-210a5134abe7.png)
![coupon_shipping](https://user-images.githubusercontent.com/38358288/181468341-75cc293e-2b7c-40b5-bae5-1759dbca7cae.png)
![shipping_mobile](https://user-images.githubusercontent.com/38358288/181468348-c9423dfd-9163-4abe-b0a0-c702508bc3c1.png)
![coupon_cart](https://user-images.githubusercontent.com/38358288/181468351-f1ceaff2-95a6-44cf-9e7a-ed65708ee690.png)
n

2022-07-28 09:34 UTC, mayun19 requested changes
design figma di bagian voucherBankLogoContainer ada background color nya apakah sudah di implementasikan ?

![image](https://user-images.githubusercontent.com/16263184/181473238-84da2c2a-be6a-48fb-ad86-3d14222a2957.png)

2022-07-28 09:38 UTC, mayun19 requested changes

2022-07-28 09:38 UTC, mayun19 commented on pages/[lng]/payment_method/index.tsx
> +import Loader from "components/Loader/Loader";
disamakan jdi 
`import Loader from 'components/Loader/Loader'`

2022-07-28 09:38 UTC, mayun19 commented on components/OrderSummaryBox/index.tsx
> +import Loader from "components/Loader/Loader";
disamakan jdi 
`import Loader from 'components/Loader/Loader'`

2022-07-28 10:05 UTC, inezamandha requested changes
boleh lihat ss berikut ini enggak yaa minta tolong ditambahkan untuk di attach
- loader component di coupon

2022-07-28 10:07 UTC, inezamandha requested changes

2022-07-28 10:07 UTC, inezamandha commented on components/OrderSummaryBox/index.tsx
> +import Loader from "components/Loader/Loader"
ini pakai kutip satu boleh?

2022-07-28 10:07 UTC, inezamandha commented on locales/en/shipping.ts
> +    "moreShipping": "Choose Other Shipping Method"
boleh dirapihin, jadi sortnya ascending tidak ya? moreShipping harusnya ada di atas

2022-07-28 10:07 UTC, inezamandha commented on locales/id/shipping.ts
> +    "moreShipping": "Pilih Methode Pengiriman Lainnya"
ini juga sama kayak di atas ya

2022-07-28 10:07 UTC, inezamandha commented on pages/[lng]/payment_method/index.tsx
> +import Loader from "components/Loader/Loader"
boleh dijadiin kutip 1?

2022-07-28 10:07 UTC, inezamandha commented on public/scss/components/whatsappOTP/LoginRegisterOTP.module.scss
> +
ini memang dibutuhkan atau kelebihan yaa space nya ke double seperti ini ada 2, sebelumnya tidak ada

2022-07-28 11:02 UTC, falmesino commented on locales/id/shipping.ts
> +    "moreShipping": "Pilih Methode Pengiriman Lainnya",
```suggestion
    "moreShipping": "Pilih Metode Pengiriman Lainnya",

```

Metode kan ya mestinya?

2022-07-28 11:04 UTC, falmesino requested changes
printilan

2022-07-28 11:45 UTC, falmesino approved these changes

2022-07-29 02:26 UTC, inezamandha approved these changes

2022-07-29 02:53 UTC, mayun19 approved these changes

2022-07-29 07:46 UTC, merged