feat: nexus 2.14.2, shipper logo, recaptcha
sirclo-solution/template-urban pull request #39
Opened 2022-08-03 08:02 UTC by DiebrataA

Summary:
- Add Shipper Logo in Coupon
- Add Recaptcha in login and register

Notes: ada perubahan css untuk FB button karena class nya undefined, tapi style nya diusahakan sama.
![image](https://user-images.githubusercontent.com/38358288/182555876-1177bea6-6eb7-47c4-b257-e789b128c3bd.png)

**Recaptcha:**
![recaptcha_urban_login](https://user-images.githubusercontent.com/38358288/182555953-e7ceb8fc-0a69-4d07-9b15-a6b324ea7d3c.png)
![recaptcha_urban_login_network](https://user-images.githubusercontent.com/38358288/182555970-5b5e3afe-63ba-4b55-ba80-12845bc00bb3.png)
![recaptcha_urban_regis](https://user-images.githubusercontent.com/38358288/182555976-cae45185-0f0c-4c05-b26a-5bfa450de12c.png)
![recaptcha_urban_regisnetwork](https://user-images.githubusercontent.com/38358288/182555985-3a7ea211-5850-4e9a-a7df-254ee165bdf1.png)

**Voucher: (cart, place order, shipping method)**
![cart_urban](https://user-images.githubusercontent.com/38358288/182556281-91214737-1f38-46e1-85fb-62c689306b3c.png)
![place_order_urban](https://user-images.githubusercontent.com/38358288/182556342-708ec557-4853-4262-b803-b3bfbbfbf978.png)
![shipping_method_urban](https://user-images.githubusercontent.com/38358288/182556356-3221878d-8f7e-4704-95e3-01e465025bfd.png)
Mobile:
![shipping_mobile](https://user-images.githubusercontent.com/38358288/182556382-332f0e77-985b-427e-bd3d-f221efbaae64.png)

2022-08-03 08:53 UTC, inezamandha requested changes
boleh tolong di ss enggak kalau ada get button whatsappnya apakah bakalan nimpa si recaptcha nya?

kalau di diff yang lain soalnya recaptchanya intinya paling bawah, get button WA nya jadi naik ke atas

*berlaku buat login dan register ya

2022-08-03 08:54 UTC, inezamandha requested changes

2022-08-03 08:54 UTC, inezamandha commented on components/LoginRegisterOTP/index.tsx
> +        getReCAPTCHAToken={getReCAPTCHAToken}
ini enggak munduran anggara?

2022-08-03 08:54 UTC, inezamandha commented on public/scss/components/PopUpVoucherCoupon.module.scss
> +  background-color: $color_white
gapakai titik koma kah anggara?

2022-08-03 08:54 UTC, inezamandha commented on public/scss/components/PopUpVoucherCoupon.module.scss
> +  background-color: $color_white
ini juga gapakai titik koma kah?

2022-08-03 08:54 UTC, inezamandha commented on public/scss/components/PopUpVoucherCoupon.module.scss
> +  padding: 8px 12px 9px 12px;
ini bisa dijadikan `padding: 8px 12px 9px;` yah

2022-08-03 08:54 UTC, inezamandha commented on public/scss/components/whatsappOTP/LoginRegisterOTP.module.scss
> +  background-repeat: no-repeat;
bisa dirapihin yaa, mungkin content paling atas, includenya di bawah content ya secara berurutan

2022-08-03 08:55 UTC, inezamandha commented
masalah FB login nya itu maksudnya stylingnya yang udah seperti di bagian (update) kan yaa alias udah bener?

2022-08-03 10:10 UTC, DiebrataA commented
> masalah FB login nya itu maksudnya stylingnya yang udah seperti di bagian (update) kan yaa alias udah bener?

iyak nezz sudah bener kok inii

2022-08-03 10:17 UTC, DiebrataA commented
also updated to 2.14.3

2022-08-03 10:40 UTC, DiebrataA commented
> boleh tolong di ss enggak kalau ada get button whatsappnya apakah bakalan nimpa si recaptcha nya?
> 
> kalau di diff yang lain soalnya recaptchanya intinya paling bawah, get button WA nya jadi naik ke atas
> 
> *berlaku buat login dan register ya

![image](https://user-images.githubusercontent.com/38358288/182588619-6142f0f2-a7fe-4227-ae9e-047db5ef370d.png)
![image](https://user-images.githubusercontent.com/38358288/182588685-cc209129-33ec-426b-9f8c-644b558e4917.png)
![image](https://user-images.githubusercontent.com/38358288/182588798-d3b025e4-48a8-449d-b6ea-a27b96bb11af.png)
![image](https://user-images.githubusercontent.com/38358288/182588827-f5f032aa-0253-44d2-ab3b-7144fc80d1b8.png)

2022-08-03 11:04 UTC, inezamandha approved these changes

2022-08-04 02:21 UTC, virginiaritonga approved these changes

2022-08-04 02:29 UTC, tiarss approved these changes

2022-08-04 02:33 UTC, merged