Review UI
sirclo-solution/template-urban pull request #5
Opened 2021-12-23 04:53 UTC by yohanavitrawati

Urban

- [x] riwayat keanggotaan kosong infonya kasi notes belum/tidak ada data
![Screen Shot 2021-12-22 at 20 58 13](https://user-images.githubusercontent.com/8541505/147104122-6c83f3c3-36aa-4985-99f8-e9777a4121fc.png)

- [x] error state & sucess waktu save info akun
![Screen Shot 2021-12-22 at 20 51 32](https://user-images.githubusercontent.com/8541505/147103126-f61f3797-903c-4161-b96f-f584aa4ba9b5.png)

- [x] checkbox di atas button bayar
![Screen Shot 2021-12-23 at 09 42 04](https://user-images.githubusercontent.com/8541505/147179803-48fcf25a-b30e-47b3-9c22-575c96fad772.png)

- [x] dibagian atas place order ketika sudah login terlihat kosong, sepertinya itu tempat checkbox untuk daftar akun
![Screen Shot 2021-12-22 at 21 06 47](https://user-images.githubusercontent.com/8541505/147105236-b19eeed7-9b27-4376-9ce1-2ff4f48458ec.png)

- [x] cart kosong ilangin order summary
![Screen Shot 2021-12-22 at 20 52 52](https://user-images.githubusercontent.com/8541505/147103327-c8d3e8b0-4144-40f9-8108-ba0d84736732.png)

- [x] tidak center ketika ga ada fb/wa login
![Screen Shot 2021-12-22 at 20 54 49](https://user-images.githubusercontent.com/8541505/147103630-b71d299c-0d53-431e-a750-97d4bd2842a0.png)

- [x] image category gepeng
![Screen Shot 2021-12-22 at 20 50 26](https://user-images.githubusercontent.com/8541505/147102929-c038ed90-5315-4a22-9680-8ff8bfd27793.png)

- [x] web title all pages
![Screen Shot 2021-12-22 at 21 00 38](https://user-images.githubusercontent.com/8541505/147104424-9f41236f-baa1-485b-82ba-307d7d4b7e05.png)

- [x] favicon 
![Screen Shot 2021-12-22 at 20 48 03](https://user-images.githubusercontent.com/8541505/147102590-8098a188-ed14-4210-bad8-45c9db5ffaaf.png)

- [x] input kota kecamatan terlalu kecil
![Screen Shot 2021-12-22 at 20 57 38](https://user-images.githubusercontent.com/8541505/147104032-ffd79aea-d81b-479c-8961-79b4d5014adc.png)

- [x] text author/date di blog 2 line jadi 1 line
![Screen Shot 2021-12-22 at 20 45 14](https://user-images.githubusercontent.com/8541505/147102277-15417ce3-2c80-4c05-a0b4-2b8b555fa155.png)

- [x] images di login mobile dihide
![Screen Shot 2021-12-22 at 20 55 33](https://user-images.githubusercontent.com/8541505/147103746-197c05d4-0388-4182-8553-34b29c9e7587.png)

- [x] font placeholder beda change password
![Screen Shot 2021-12-22 at 20 48 32](https://user-images.githubusercontent.com/8541505/147102650-1122bb66-7907-4022-9ed9-3901f2c8da54.png)

- [x] padding kiri popup success add to cart
![Screen Shot 2021-12-22 at 20 59 35](https://user-images.githubusercontent.com/8541505/147104321-c270f92c-4da7-46c7-9f1b-70f8641fa08e.png)

- [x] input nama di account jadi double 
![Screen Shot 2021-12-22 at 20 48 59](https://user-images.githubusercontent.com/8541505/147102709-74bb9eb0-b865-4677-a578-f3789cb59122.png)

- [ ] ketika sticky, footer diilangin di mobile, **_note:sudah konfirm ke Arie dan ga jadi karena di template lain beberapa ada yg seperti itu juga_**

- [ ] icon tutup buka di additional info product details -> **_ini belum, bawaan dari nexus ga bisa, kalo custom sepertinya effortnya lumayan, mungkin bisa dibuatkan task terpisah?_**

2021-12-23 09:16 UTC, muhammadanova requested changes

2021-12-23 09:16 UTC, muhammadanova commented on pages/[lng]/blog/index.tsx
> +    SEO: { title: `Blog` },
ga dari i18n kah mba?

2021-12-23 09:16 UTC, muhammadanova commented on pages/[lng]/lookbook/categories/index.tsx
> +    SEO: { title: `lookbook` },
Ini jg ga dari i18n

2021-12-23 10:38 UTC, inezamandha requested changes

2021-12-23 10:38 UTC, inezamandha commented on locales/en/home.ts
>      "productCategory": "Category products",
ini kayaknya bisa di sort terlebih dahulu mba

2021-12-23 10:38 UTC, inezamandha commented on locales/id/home.ts
>      "productCategory": "Kategori produk",
ini juga sama yaa mba di sort sesuai alfabet

2021-12-23 10:38 UTC, inezamandha commented on public/scss/components/whatsappOTP/LoginRegisterOTP.module.scss
> +  margin:0 12px;
bisa dikasih space setelah :

2021-12-23 10:38 UTC, inezamandha commented on public/scss/pages/Account.module.scss
> +    color: #000000;
ada color variable untuk warna hitam ini tidak mba?

2021-12-24 02:39 UTC, inezamandha approved these changes

2021-12-24 02:44 UTC, inezamandha requested changes

2021-12-24 02:44 UTC, inezamandha commented on public/scss/pages/Account.module.scss
> +    color: $color_tiktok;
ini namanya unik juga! tapi color_tiktok adanya di utils, tapi colors.scss nya juga ada di base. kedua filenya isinya berbeda jadi yang dipakai apakah di fodler base atau di utils ya..

2021-12-24 02:46 UTC, inezamandha approved these changes

2021-12-24 06:54 UTC, muhammadanova approved these changes

2021-12-27 02:44 UTC, falmesino approved these changes

2021-12-27 06:32 UTC, handripangestiaji approved these changes

2021-12-27 06:46 UTC, merged