fix: implement filter shipping method, wording coupon, getButton
sirclo-solution/template-urban pull request #52
Opened 2022-09-15 05:02 UTC by inezamandha

Tampilan:

Filter Shipping Method sekaligus ada wording voucher diubah ke kupon

<img width="960" alt="image" src="https://user-images.githubusercontent.com/45808774/190316898-1c70d059-fd55-4611-8c24-25767e6fbabd.png">

<img width="157" alt="image" src="https://user-images.githubusercontent.com/45808774/190316925-510c86a3-7d24-454c-aee3-e88d9a3d1921.png">

Tanpa Filter Shipping aman

<img width="960" alt="image" src="https://user-images.githubusercontent.com/45808774/190317373-5351a587-9578-41a4-b427-a9004481866e.png">

<img width="156" alt="image" src="https://user-images.githubusercontent.com/45808774/190317404-3d36f45b-1bd5-47e2-b875-450df30ce100.png">

GetButton sudah tidak naik

<img width="960" alt="image" src="https://user-images.githubusercontent.com/45808774/190317879-c8be56bd-b369-423d-ba96-7748221ec857.png">

<img width="158" alt="image" src="https://user-images.githubusercontent.com/45808774/190317912-d5c194e8-851d-45d1-8690-7e23b16b880e.png">

Login
<img width="960" alt="image" src="https://user-images.githubusercontent.com/45808774/190318229-fca9ea69-007b-4fe4-bba3-fa58bb553cff.png">

<img width="157" alt="image" src="https://user-images.githubusercontent.com/45808774/190318281-e2c458fd-78ee-4e05-a64f-598a74da01a7.png">

Register

<img width="155" alt="image" src="https://user-images.githubusercontent.com/45808774/190318668-01bb382f-5f8f-4e7f-a043-c99243583248.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/45808774/190318680-e874ce31-513a-49e1-8771-6b2c75bb4429.png">

**otp tidak bisa diakses harus disetup dulu

---
Make Sure sajha

Kupon (bank dan shipping sudah samping sampingan)

<img width="154" alt="image" src="https://user-images.githubusercontent.com/45808774/190316966-f963bfc3-faa6-48e2-b0bd-7efdd2e53c87.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/45808774/190317021-9b91da8d-aa93-4536-8f6a-8010be8ad055.png">

2022-09-15 09:41 UTC, sultanfariz approved these changes

2022-09-15 10:04 UTC, muhammadanova requested changes

2022-09-15 10:04 UTC, muhammadanova commented on pages/[lng]/register/index.tsx
> +import Router, { useRouter } from 'next/router'
Router nya unused kah?

2022-09-15 10:09 UTC, mayun19 approved these changes

2022-09-15 10:13 UTC, inezamandha commented on pages/[lng]/register/index.tsx
> +import Router, { useRouter } from 'next/router'
yang `Route` kepakai mas di bagian sinii
<img width="662" alt="image" src="https://user-images.githubusercontent.com/45808774/190378308-6de9f262-76b2-44ca-aac2-019f62be56e7.png">

apakah gapapa atau bagaimana yaa mas?

2022-09-15 10:16 UTC, inezamandha commented on pages/[lng]/register/index.tsx
> +import Router, { useRouter } from 'next/router'
atau baiknya langsung pakai `router.push` aja jadi Routernya dihapus mas?

2022-09-16 03:24 UTC, muhammadanova approved these changes

2022-09-16 03:41 UTC, merged