fix: manual and map address input on placeorder
sirclo-solution/template-urban pull request #57
Opened 2022-09-29 08:59 UTC by ardiankristo

Screenshots:

2022-09-29 09:28 UTC, virginiaritonga commented
kalo di figma ada jakar dari map ke border containernya to mungkin bisa dipastikeun kembali
<img width="544" alt="Screen Shot 2022-09-29 at 16 26 17" src="https://user-images.githubusercontent.com/43097333/192994780-9093719f-eb3a-4411-bc99-648e2068f8d6.png">

<img width="246" alt="Screen Shot 2022-09-29 at 16 24 46" src="https://user-images.githubusercontent.com/43097333/192995053-49a67ebc-9488-4e0d-affa-816cab82bd13.png">

2022-09-29 09:35 UTC, falmesino requested changes
request changes perintilan

2022-09-29 09:35 UTC, falmesino commented on public/scss/components/Map.module.scss
> +  padding: 28px 18px 10px 18px !important;
```suggestion
  padding: 28px 18px 10px !important;
```

dibikin begini juga bisa

2022-09-29 09:35 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +  @include fixedHeight(360px);
include taro paling atas pacc

2022-09-29 09:35 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +  @include lineHeight(24);
```suggestion
  @include typographyBuilder(400, 16, 24);
```

pake mixin ini bisa sepertinya

2022-09-29 09:35 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +  padding: 8px 20px 0 20px;
```suggestion
  padding: 8px 20px 0;
```

giniin aja pacc biar hemat

2022-09-29 09:35 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +  @include lineHeight(24);
```suggestion
  @include typographyBuilder(400, 14, 24);
```

pakai mixin ini pacc

2022-09-29 09:35 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +      @include fixedHeight(100px);
```suggestion
      @include fixedSize(100px);
```

pakay mixin ini pacc

2022-09-29 09:35 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +      @include fixedHeight(133px);
```suggestion
      @include fixedSize(133px);
```
pakay mixin ini pacc

2022-09-29 09:35 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +
```suggestion
```

hapus pacc

2022-09-29 09:35 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +  line-height: 16px;
```suggestion
  @include typographyBuilder(500, 12, 16);
```

pakay mixin ini pacc

2022-09-29 09:35 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +  font-size: 12px;
```suggestion
  @include fontSize(12);
```

pakay mixin ini pacc

2022-09-29 09:35 UTC, falmesino commented on public/scss/components/Map.module.scss
> +  @include RegulerReguler;
```suggestion
  @include flex(row, center, center);
  @include RegulerReguler;
  color: $color_text_grey;
```

include taro paling atas pacc

2022-09-29 09:40 UTC, virginiaritonga commented on locales/en/map.ts
> +    "inputWithMap": "Enter the address using the map",
dua locales ini bisa dipindah ke bawah "cityDistrictNotFound" agar sorted by alphabet

2022-09-29 09:40 UTC, virginiaritonga commented on locales/en/placeOrder.ts
> +    "submitButton": "Place Order",
tolong sort by alphabet yak

2022-09-29 09:40 UTC, virginiaritonga commented on locales/en/global.ts
> +    "save": "Save"
pindah ke atasnya (locales disort by alphabet)

2022-09-29 09:40 UTC, virginiaritonga commented on public/scss/pages/Placeorder.module.scss
> +  &[class$="-6us33n"]
kyknya ini generated uniquely, ada cara lain kah manggil elemen ini?

2022-09-29 09:40 UTC, virginiaritonga commented on public/scss/pages/Placeorder.module.scss
> +    &[class*=" css-1pahdxg"]
kyknya ini generated uniquely, ada cara lain kah manggil elemen ini?

2022-09-29 09:40 UTC, virginiaritonga commented on public/scss/pages/Placeorder.module.scss
> +    &[class*=" css-26l3qy"]
kyknya ini generated uniquely, ada cara lain kah manggil elemen ini?

2022-09-29 09:40 UTC, virginiaritonga commented on public/scss/pages/Placeorder.module.scss
> +    &[class*=" css-1qjra3o"]
kyknya ini generated uniquely, ada cara lain kah manggil elemen ini?

2022-09-29 10:59 UTC, mayun19 requested changes

2022-09-29 10:59 UTC, mayun19 commented on public/scss/pages/Placeorder.module.scss
> +  // NOTE: IF applied to street will effect country & address detail label, but I can't find a way to apply this to country only
ini terkait apa ya? semisal udh ga dipake bisa dihapus saja

2022-09-29 10:59 UTC, mayun19 commented on public/scss/pages/Placeorder.module.scss
> +      &::before
ini boleh dikasih tab enter biar lebih rapi ?

2022-09-29 10:59 UTC, mayun19 commented on public/scss/pages/PlaceorderV2.module.scss
> +  height: 100%;
ini bisa pake mixin fixedWidth kah ?

2022-09-29 10:59 UTC, mayun19 commented on public/scss/pages/PlaceorderV2.module.scss
> +  display: flex;
ini bisa di hapus sudah pake mixin flex diatas

2022-09-29 10:59 UTC, mayun19 commented on public/scss/pages/PlaceorderV2.module.scss
> +  position: relative;
ini sepertinya bisa pake mixin position

2022-09-29 10:59 UTC, mayun19 commented on public/scss/pages/PlaceorderV2.module.scss
> +  height: 20px;
ini bisa pakai mixin @include fixedSize(20px);

2022-09-29 10:59 UTC, mayun19 commented on public/scss/pages/PlaceorderV2.module.scss
> +    {
ini sepertinya bisa pakai mixin @include fixedSize(103px);

2022-09-30 02:24 UTC, sultanfariz commented on public/scss/pages/Placeorder.module.scss
> +    text-overflow: ellipsis;
sepertinya bisa diganti mixin
```suggestion
    @include textOverflow();
```

2022-09-30 02:30 UTC, mayun19 commented
input kode pos pada popup maps desktop yg terimplement width nya sepertinya lebih dari di figma ini, mungkin bisa dipastikeun kembali

input detail alamat di figma nya lebih tinggi dari ukuran input lain nya, mungkin bisa dipastikeun kembali

![image](https://user-images.githubusercontent.com/16263184/193176192-fe5cca48-e766-47e8-91d1-a6e00107bb56.png)

warna dan font-weight nama jalan dan deskripsi jalan sepertinya juga masi belum sesuai dengan figma, mungkin bisa dipastikeun kembali

font-weight "Kesulitan menemukan lokasi Anda di peta?" yang terimplement terlihat lebih tebal dari figma nya mas
![image](https://user-images.githubusercontent.com/16263184/193177196-153ec2b4-8995-473b-bf06-f60123b55b6e.png)


Request  tampilan pop-up map di halaman account dan shipping method mas

2022-09-30 02:47 UTC, ardiankristo commented
![Screenshot from 2022-09-30 09-44-34](https://user-images.githubusercontent.com/40454642/193179310-d0c85420-6485-4d10-8ac4-a2b279ac8f21.png)
![Screenshot from 2022-09-30 09-44-37](https://user-images.githubusercontent.com/40454642/193179314-d55c338d-37f4-4b81-b954-314dd9039649.png)
![Screenshot from 2022-09-30 09-44-40](https://user-images.githubusercontent.com/40454642/193179317-57e4a034-0c41-47fc-9fc2-d61f5eefee89.png)

Screenshot terkait review nya mbak @mayun19

2022-09-30 02:55 UTC, mayun19 commented
tambahan lagi mas, ini di input negara ga ada "|" pas samping icon dropdown

![image](https://user-images.githubusercontent.com/16263184/193180324-d72feb43-0657-4caa-86f1-ac23926ba45e.png)

2022-09-30 03:00 UTC, falmesino requested changes
mazih ads printilans printiluns

2022-09-30 03:00 UTC, falmesino commented on public/scss/pages/Placeorder.module.scss
> +  padding: 18px 0 0 0;
```suggestion
  padding: 18px 0 0;
```

Bisa begini juga

2022-09-30 03:00 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +  overflow: auto;
```suggestion
  -moz-box-flex: 1;
  flex-grow: 1;
  overflow: auto;
  
  @media screen and (max-width: 479px)
  {
    margin-top: 0;
    padding-top: 72px;
  }
```

media queries taro bawah pacc biar rapi

2022-09-30 03:00 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +      @include fixedSize(103px !important);
```suggestion
      @include fixedSize(103px, true);
```

kalo tydac salah biar jadi `!important` tuh ada di parameter kedua pacc, dibikin jadi `true`

2022-09-30 03:00 UTC, falmesino commented on public/scss/pages/PlaceorderV2.module.scss
> +    margin: 20px 16px 0 16px;
```suggestion
    margin: 20px 16px 0;
```

Begini juga bisa, padding kiri-nya kan sama kayak yang kanan.

2022-09-30 03:00 UTC, falmesino commented on public/scss/pages/Placeorder.module.scss
> +    &[class*=" css-1qjra3o"]
yang teks random-nya jangan dimasukin ke selector, awalan sama akhirannya aja seperti ini:

misalnya className-nya itu ` css-1qjra3o-container`...

```
&[class^=" css-"][class$="-container"] {
  // ...
}

// kalau misalnya yang atas gak kena...
&[class*=" css-"][class$="-container"] {
  // ...
}
```

2022-09-30 04:41 UTC, muhammadanova approved these changes

2022-09-30 04:41 UTC, muhammadanova commented on public/scss/pages/PlaceorderV2.module.scss
> +  position: fixed;
Ada mixins fixed ini To

2022-09-30 04:41 UTC, muhammadanova commented on public/scss/pages/PlaceorderV2.module.scss
> +  position: absolute;
Ada mixins absolute ini To

2022-09-30 04:41 UTC, muhammadanova commented on public/scss/pages/PlaceorderV2.module.scss
> +    position: absolute;
Ada mixins absolute ini To

2022-09-30 04:41 UTC, muhammadanova commented on public/scss/pages/PlaceorderV2.module.scss
> +  position: absolute;
Ada mixins absolute ini To

2022-09-30 06:39 UTC, inezamandha requested changes

2022-09-30 06:39 UTC, inezamandha commented on public/scss/pages/Placeorder.module.scss
> +    }
di bawah sini boleh dikasih enter?

2022-09-30 06:39 UTC, inezamandha commented on public/scss/pages/Placeorder.module.scss
> +    }
di bawah sini boleh dikasih enter?

2022-09-30 06:39 UTC, inezamandha commented on public/scss/pages/Placeorder.module.scss
> +    }
di bawah sini boleh dikasih enter?

2022-09-30 06:46 UTC, inezamandha commented
di di bagian yang tanggal lahir kayaknya belum proposional yaa datenya

<img width="244" alt="image" src="https://user-images.githubusercontent.com/45808774/193207504-6084d503-24db-4bdd-b698-fdd0833a9630.png">

kalau gasalah aku pernah mengerjakan hal serupa (pernah ada balikan dari QA karena ini rasanya jarang2)
nah contohnya di sini yaa
sebelumnya: https://phabricator.sirclo.com/R380:255eaf04ad2f3cb4e6a14c919d12642676573df8 (jarang jarang)
setelahnya: https://phabricator.sirclo.com/R380:831133a2ab843d905f940899e612f999c3b45c40

ada di lumiville

mungkin boleh diubah juga mas biar lebih rapii?

2022-09-30 06:49 UTC, inezamandha commented
ini di hover atau di klik salah satunya apakah ada warna yang berbeda gitu engga yaa? (desktop/mobile)
<img width="143" alt="image" src="https://user-images.githubusercontent.com/45808774/193208338-22014ce9-d9e8-4c9f-950a-d5bb27dbc286.png">

warnanya macam begini
<img width="466" alt="image" src="https://user-images.githubusercontent.com/45808774/193208396-f24921e0-ebc8-4400-a283-3375f4f56107.png">

2022-09-30 07:48 UTC, muhammadanova approved these changes

2022-09-30 08:12 UTC, ardiankristo commented
Update PoW @inezamandha 
![Screenshot from 2022-09-30 15-11-34](https://user-images.githubusercontent.com/40454642/193223955-b209b893-7584-4ace-8563-b104cece7918.png)
![Screenshot from 2022-09-30 15-11-38](https://user-images.githubusercontent.com/40454642/193223966-9703c6c0-1eb7-4fd4-a426-59aef57d9c35.png)

2022-09-30 08:23 UTC, inezamandha approved these changes

2022-09-30 08:26 UTC, virginiaritonga approved these changes

2022-10-03 07:02 UTC, ardiankristo commented
Adjustment map pop up di /account dan /shipping_method:

![Screenshot from 2022-10-03 14-01-04](https://user-images.githubusercontent.com/40454642/193518436-d08126ca-f122-4b0d-af55-2f6dfec9fcd5.png)
![Screenshot from 2022-10-03 09-44-08](https://user-images.githubusercontent.com/40454642/193518411-7b221bbb-5b70-4878-9de9-b900f496d389.png)
![Screenshot from 2022-10-03 09-56-12](https://user-images.githubusercontent.com/40454642/193518423-34ea76e6-7b8b-4022-98cf-c4e5302322d9.png)
![Screenshot from 2022-10-03 13-38-29](https://user-images.githubusercontent.com/40454642/193518429-707ea560-cad7-43e1-b1ae-125e9afddc2f.png)

2022-10-04 04:05 UTC, ardiankristo commented
Ini ya mbak @mayun19 :pray: 

![Screenshot from 2022-10-04 11-03-57](https://user-images.githubusercontent.com/40454642/193731897-62aeba45-0eab-40ec-9c08-abba08f6c218.png)
![Screenshot from 2022-10-04 11-03-59](https://user-images.githubusercontent.com/40454642/193731912-35ac81ac-422c-4262-9ac6-7c30c00a55dd.png)

2022-10-04 04:15 UTC, mayun19 approved these changes

2022-10-04 04:18 UTC, ardiankristo commented
Map pop up di /account button back nya tidak berfungsi jadi saya timpa dengan input search nya

![Screenshot from 2022-10-04 11-09-39](https://user-images.githubusercontent.com/40454642/193733211-82f2c86f-2aa8-4bb0-a332-3678f8cf56cf.png)
[Screencast from 03-10-22 16:38:44.webm](https://user-images.githubusercontent.com/40454642/193733257-e6a540fa-abd2-45f6-8a28-4f1c02dd909a.webm)

![Screenshot from 2022-10-04 11-09-13](https://user-images.githubusercontent.com/40454642/193733205-da256d02-f4f3-40d5-ac44-22ee24e50089.png)

2022-10-04 04:27 UTC, tiarss commented on public/scss/components/Map.module.scss
> +    z-index: 1;
ini ada 2

2022-10-04 04:29 UTC, tiarss commented on public/scss/components/Map.module.scss
> +    z-index: 1;
ada dua nih mas..

2022-10-04 04:32 UTC, tiarss approved these changes

2022-10-04 04:40 UTC, sultanfariz approved these changes

2022-10-04 04:46 UTC, falmesino approved these changes

2022-10-04 05:05 UTC, merged