fix: checkout form v2 wording, dropdown & pop up container
sirclo-solution/template-urban pull request #59
Opened 2022-10-05 08:24 UTC by ardiankristo

Balikan testing QA

2022-10-05 10:35 UTC, ardiankristo commented
Fix wording pop up address:
![Screenshot from 2022-10-05 17-35-12](https://user-images.githubusercontent.com/40454642/194040980-6f199143-9523-4f77-8053-18e66ad899ff.png)
![Screenshot from 2022-10-05 17-35-18](https://user-images.githubusercontent.com/40454642/194040987-f3275f26-7080-48d4-b36e-610f65334a13.png)

2022-10-05 10:48 UTC, muhammadanova requested changes

2022-10-05 10:48 UTC, muhammadanova commented on public/scss/pages/Placeorder.module.scss
> +      margin-top: 0px;
margin-top: 0; dulu diajarin mang otoy ga perlu pake px kalo 0

2022-10-05 10:48 UTC, muhammadanova commented on locales/id/placeOrder.ts
> +    "provincePlaceholder": "Contoh: Ontario",
Gua kok asing ya Ontario

2022-10-05 10:48 UTC, muhammadanova commented on locales/en/placeOrder.ts
> +    "cityPlaceholder": "Ex: Ottawa",
Gua jg asing Ottawa

2022-10-05 10:50 UTC, mayun19 commented
wording dalam bahasa inggris nya aman mas ?

2022-10-05 10:50 UTC, falmesino commented on locales/id/placeOrder.ts
> +    "provincePlaceholder": "Contoh: Ontario",
teks "provincePlaceholder"-nya pake yang udah ada aja mungkin pak?

Ontario itu di Banyuwangi btw

2022-10-05 10:51 UTC, falmesino commented on locales/en/placeOrder.ts
> +    "cityPlaceholder": "Ex: Ottawa",
teks "cityPlaceholder"-nya pake yang udah ada aja di template lain mungkin pak?

2022-10-05 11:54 UTC, sultanfariz approved these changes

2022-10-06 02:10 UTC, ardiankristo commented on locales/id/placeOrder.ts
> +    "provincePlaceholder": "Contoh: Ontario",
ini nyesuaiin desain figma nya buat placeholder di international pak
https://www.figma.com/file/meOtFhWTvK519ixxC8Nv3x/%5BVENDOR%5D-Urban?node-id=2646%3A21380

2022-10-06 02:10 UTC, ardiankristo commented on locales/en/placeOrder.ts
> +    "cityPlaceholder": "Ex: Ottawa",
ini juga https://www.figma.com/file/meOtFhWTvK519ixxC8Nv3x/%5BVENDOR%5D-Urban?node-id=2646%3A21380

2022-10-06 02:27 UTC, ardiankristo commented
Wording map pop up

Indonesia
(domestik)
![Screenshot from 2022-10-06 09-16-54](https://user-images.githubusercontent.com/40454642/194200295-6810cde0-0e99-4c4b-891f-43ded67920f5.png)
(internasional)
![Screenshot from 2022-10-06 09-17-04](https://user-images.githubusercontent.com/40454642/194200358-0be27385-bfc7-4696-9a25-28057b04edbf.png)

Inggris
(domestik)
![Screenshot from 2022-10-06 09-23-37](https://user-images.githubusercontent.com/40454642/194200482-640bf9f5-2b85-48df-be0a-fce877ab38c1.png)
(internasional)
![Screenshot from 2022-10-06 09-23-45](https://user-images.githubusercontent.com/40454642/194200506-36c4b9ef-bd43-450a-88ae-4b02de2d923c.png)

2022-10-06 02:36 UTC, inezamandha commented on locales/en/placeOrder.ts
> +    "cityPlaceholder": "Ex: Ottawa",
karena contoh di figmanya sepertinya kanada ya, jadi provinsi dan kotanya negara negara kanada. si ontario dan ottawa

2022-10-06 02:36 UTC, inezamandha approved these changes

2022-10-06 02:39 UTC, mayun19 approved these changes

2022-10-06 02:53 UTC, tiarss approved these changes

2022-10-06 03:02 UTC, muhammadanova approved these changes

2022-10-06 03:14 UTC, merged