feat(coupon): improvement coupon ui component on template
sirclo-solution/template-urban pull request #61
Opened 2022-10-07 07:18 UTC by muhammadanova

To do :
- Improve style coupon popup full device (1 object style OrderSummaryBox & ListPaymentMethod)
- Remove isCouponAccordion (OrderSummaryBox & ListPaymentMethod)
- Add props function onSuccessCopyCodeCoupon (OrderSummaryBox & ListPaymentMethod)
- Add copy icons
- Add locales coupon
- Points popup as is
- Up version to 2.16.1 cause 2.16.4 have bug on ListPaymentMethod selected

SS pow : 

<img width="421" alt="Screen Shot 2022-10-07 at 14 12 21" src="https://user-images.githubusercontent.com/49178784/194494661-6f90d912-539e-4381-aebf-01e6d100a9f2.png">
<img width="421" alt="Screen Shot 2022-10-07 at 14 12 33" src="https://user-images.githubusercontent.com/49178784/194494690-2e025594-90d4-4e60-ba2d-7cf6791d63e9.png">
<img width="421" alt="Screen Shot 2022-10-07 at 14 12 43" src="https://user-images.githubusercontent.com/49178784/194494700-48d98c52-8287-4b56-a73f-c9cecc720529.png">
<img width="421" alt="Screen Shot 2022-10-07 at 14 13 15" src="https://user-images.githubusercontent.com/49178784/194494712-84bf2c2b-f62f-4d1f-8989-a1b3c55c37b5.png">
<img width="360" alt="Screen Shot 2022-10-07 at 14 13 56" src="https://user-images.githubusercontent.com/49178784/194494727-c7d833a7-84e6-46b8-9c7b-93b995d4bf6b.png">
<img width="360" alt="Screen Shot 2022-10-07 at 14 14 06" src="https://user-images.githubusercontent.com/49178784/194494742-9f9e1754-b0bd-4af4-b025-4b24820abd48.png">
<img width="360" alt="Screen Shot 2022-10-07 at 14 14 16" src="https://user-images.githubusercontent.com/49178784/194494749-19ab3705-3cc3-48fe-94c8-0e7b7400a4c6.png">
<img width="360" alt="Screen Shot 2022-10-07 at 14 14 25" src="https://user-images.githubusercontent.com/49178784/194494764-886ce68d-89b5-4030-96b8-3e098d03ccdc.png">
<img width="1431" alt="Screen Shot 2022-10-07 at 14 14 53" src="https://user-images.githubusercontent.com/49178784/194494770-d2319cb4-096e-49af-a6ae-a24003190803.png">
<img width="1431" alt="Screen Shot 2022-10-07 at 14 15 13" src="https://user-images.githubusercontent.com/49178784/194494779-96768b4d-2fc2-4e0c-ac3a-69cd2063897a.png">
<img width="1431" alt="Screen Shot 2022-10-07 at 14 15 25" src="https://user-images.githubusercontent.com/49178784/194494789-f0a4c2be-f63f-409c-b039-cfc64c22d0b3.png">
<img width="1431" alt="Screen Shot 2022-10-07 at 14 15 39" src="https://user-images.githubusercontent.com/49178784/194494803-ebd233f0-7177-47e2-8b31-13ca2fab6c10.png">
<img width="1431" alt="Screen Shot 2022-10-07 at 14 15 58" src="https://user-images.githubusercontent.com/49178784/194494812-0e34f5e8-5aab-40c8-b669-b8c573975e30.png">
<img width="1431" alt="Screen Shot 2022-10-07 at 14 16 07" src="https://user-images.githubusercontent.com/49178784/194494823-0ecc10a4-9f47-40ea-b9d0-39ac30b17245.png">
<img width="1431" alt="Screen Shot 2022-10-07 at 14 16 25" src="https://user-images.githubusercontent.com/49178784/194494827-c5e6047e-bd87-4f1a-b4fa-324697ff7044.png">
<img width="1431" alt="Screen Shot 2022-10-07 at 14 16 32" src="https://user-images.githubusercontent.com/49178784/194494841-0b538a04-16fe-4abb-a2ed-05302b7aa106.png">

2022-10-07 07:35 UTC, mayun19 requested changes

2022-10-07 07:35 UTC, mayun19 commented on public/scss/components/PopUpVoucherCoupon.module.scss
> +    width: 13px;
ini bisa pakai fixedSize mas

2022-10-07 07:35 UTC, mayun19 commented on public/scss/components/PopUpVoucherCoupon.module.scss
> +      width: 14px;
ini bisa pakai fixedSize mas

2022-10-07 07:35 UTC, mayun19 commented on public/scss/components/PopUpVoucherCoupon.module.scss
> +  @include absolute(8px, 12px);
bisa ditaruh di bawahnya @extend mas
```suggestion
  @extend .btn
  @include ExtraSmallReguler;
  @include absolute(8px, 12px);
```

2022-10-07 07:35 UTC, mayun19 commented on public/scss/components/PopUpVoucherCoupon.module.scss
> +  z-index: 1;
z-index nya bisa ditaruh di bawahnya @include

2022-10-07 08:26 UTC, inezamandha commented
mas aku mau nanya saja
kalau dia kosong enggak ada logonya memang apakah seperti itu (ada background abu abunya tanpa logo)?
<img width="524" alt="image" src="https://user-images.githubusercontent.com/45808774/194508331-88b9231b-23bb-418d-960e-df88b46b91ce.png">

atau seharusnya seperti punya anggara?
<img width="498" alt="image" src="https://user-images.githubusercontent.com/45808774/194508377-8cd89777-27b6-417a-89e4-91b9f374edc1.png">

2022-10-07 08:27 UTC, inezamandha reviewed
pertanyaannya ada di atas ya hehe terkait desainnya

2022-10-07 08:39 UTC, mayun19 approved these changes

2022-10-07 09:13 UTC, falmesino requested changes

2022-10-07 09:13 UTC, falmesino commented on pages/[lng]/payment_method/index.tsx
>    const linksBreadcrumb = [`${i18n.t("header.home")}`, i18n.t("placeOrder.checkOrder")]
```suggestion
  const linksBreadcrumb = [i18n.t("header.home"), i18n.t("placeOrder.checkOrder")]
```

giniin boleh pacc? gatel saia liatnya

2022-10-07 09:13 UTC, falmesino commented on public/scss/components/PopUpVoucherCoupon.module.scss
> +    max-height: 100%;
```suggestion
    @include fixedHeight(100%);
```

udah ada mixin ini kan ya kalo urban

2022-10-07 09:13 UTC, falmesino commented on public/scss/components/PopUpVoucherCoupon.module.scss
> +  @include fixedHeight(100%);
```suggestion
  @include fixedSize(100%);
```

pake mixin ini saja ngab

2022-10-07 09:17 UTC, falmesino requested changes
request changes perintilan

2022-10-07 09:17 UTC, inezamandha approved these changes

2022-10-10 03:48 UTC, falmesino approved these changes

2022-10-10 06:38 UTC, merged