fix: product child category dropdown
sirclo-solution/template-urban pull request #69
Opened 2022-10-22 04:19 UTC by ardiankristo

2022-10-24 10:48 UTC, falmesino requested changes

2022-10-24 10:48 UTC, falmesino commented on public/scss/components/ProductCategory.module.scss
> +    }
ini si keyframesnya mungkin bisa ditaro ke dalem /public/scss/utils/_keyframes.scss pak

sama ada pertanyaan,
kalo misalnya dropdown category-nya dibuka, terus ditutup, trus dibuka lagi
animasinya masih ada kah?

2022-10-25 02:21 UTC, inezamandha commented
kalau dari aku mau nanyanya apakah di homepage ini memang diperbolehkan ada subchild dll buat di categorynya? Atau sebenernya cuma parentnya aja yaa?

2022-10-25 02:42 UTC, ardiankristo commented on public/scss/components/ProductCategory.module.scss
> +    }
updated pak, ini animasinya masih ada
[Screencast from 25-10-22 09:39:24.webm](https://user-images.githubusercontent.com/40454642/197669577-b083f8f2-1f9c-4ad0-8100-d0d3c39b279b.webm)

2022-10-25 02:42 UTC, ardiankristo commented
> kalau dari aku mau nanyanya apakah di homepage ini memang diperbolehkan ada subchild dll buat di categorynya? Atau sebenernya cuma parentnya aja yaa?

hmm kalo ini kurang tahu, perlu ditanyakan designer dulu kah? soalnya ini cuma sekedar mbenerin yang kelihatan breaking aja hehe

2022-10-25 03:01 UTC, falmesino approved these changes

2022-10-25 03:19 UTC, inezamandha commented
> hmm kalo ini kurang tahu, perlu ditanyakan designer dulu kah? soalnya ini cuma sekedar mbenerin yang kelihatan breaking aja hehe

mungkin iya kali yah mas apa perlu ditanyakan ke desainer dulu ya... soalnya aku juga lupa hahaha requirementsnya seperti apa. kalau lihat di template lain kayak merlin, lastino kebetulan bentuknya bukan list ya... tapi cuma parentnya aja kalau mau lebih lengkapnya pas lihat semua gitu (?)

Lastino

<img width="960" alt="image" src="https://user-images.githubusercontent.com/45808774/197673474-7da40ac1-3191-4f8d-a1be-0b643cb0189e.png">

<img width="423" alt="image" src="https://user-images.githubusercontent.com/45808774/197673750-b42d99b8-bdd1-4a9e-aac3-4637dec7a86e.png">

Sama bagian dalamnya alias /categories juga yang subchild nya gak masuk... klik ke lihat semua
Urban (tidak ada nike dan adidas)
<img width="960" alt="image" src="https://user-images.githubusercontent.com/45808774/197674322-863424e7-1c13-496d-a9aa-48c7b83d161f.png">

jadi aku juga agak bingung baiknya gimana hahaha

2022-10-25 03:42 UTC, ardiankristo commented
oiya barusan ngecek [figma](https://www.figma.com/file/meOtFhWTvK519ixxC8Nv3x/%5BVENDOR%5D-Urban?node-id=2113%3A17980) nya juga emang ngga ada model dropdown child category nya sih, berarti child category emang gabisa diakses kah? soalnya di /categories kan juga ga muncul, kalo di home ga muncul juga jadinya gaada tempat ngakses kecuali nambahin navigasi(?)

2022-10-25 06:35 UTC, ardiankristo commented
![Screenshot from 2022-10-25 13-34-45](https://user-images.githubusercontent.com/40454642/197699869-1381d8e8-7648-4c56-b0d3-6db186d43299.png)
![Screenshot from 2022-10-25 13-34-40](https://user-images.githubusercontent.com/40454642/197699850-3ec85b5e-984d-435c-b7b4-035ba2abf2f5.png)

2022-10-25 06:37 UTC, inezamandha approved these changes

2022-10-25 06:44 UTC, tiarss approved these changes

2022-10-25 08:17 UTC, mayun19 approved these changes

2022-10-25 10:28 UTC, merged