fix: checkout button shipping 0
sirclo-solution/template-urban pull request #72
Opened 2022-10-27 15:08 UTC by yohanavitrawati

### Problem:
- Tidak bisa checkout ketika custom shipping 0, button checkout disabled
![Screen Shot 2022-10-27 at 20 52 20](https://user-images.githubusercontent.com/8541505/198328435-c8352357-8f9c-41dc-bb3f-483132b0336b.png)

### Root Cause:
- Menggunakan custom button yang ditaruh di bagian kiri, bukan dari component order summary box

### Solusi:
- Kembali menggunakan button di component order summary box.
- Di page place order, custom shipping button ditaruh di kanan, dan di shipping method juga dipindah ke kanan supaya seragam
- Disabled shipping yang tidak bisa digunakan supaya ga bisa diklik
![Screen Shot 2022-10-27 at 20 54 53](https://user-images.githubusercontent.com/8541505/198329445-2879dd4f-3e34-4c0b-8e98-145427242407.png)

![Screen Shot 2022-10-27 at 20 53 33](https://user-images.githubusercontent.com/8541505/198329438-b994346f-134c-4966-a814-5d038c2163ee.png)

### Others:
- Benerin checkbox supaya tepat berada di tengah buletan itemnya
- Kecilin sedikit tulisan Tentukan titik alamat supaya lebih rapi

2022-10-28 02:09 UTC, sultanfariz approved these changes

2022-10-28 08:09 UTC, DiebrataA approved these changes

2022-10-31 03:34 UTC, mayun19 approved these changes

2022-10-31 04:00 UTC, tiarss approved these changes

2022-10-31 04:22 UTC, inezamandha approved these changes

2022-10-31 04:54 UTC, falmesino requested changes
request change

2022-10-31 04:54 UTC, falmesino commented on public/scss/pages/ShippingMethod.module.scss
> +  &[class*=disabled]
```suggestion
  &[class*="disabled"]
```

alangkah baiknya dikasih kutip dua mba

2022-10-31 07:08 UTC, falmesino approved these changes

2022-10-31 07:36 UTC, merged