feat: product highlight list page
sirclo-solution/template-urban pull request #82
Opened 2022-11-24 07:54 UTC by rafirm29

## Summary
Original task: https://phabricator.sirclo.com/T41721
- Bump nexus to 2.17.4
- Implement `products/[slug].tsx` page
- Enable show products amount ("menampilkan xx hasil")

## Screenshots
### Desktop
![image](https://user-images.githubusercontent.com/68508069/203722172-9d21b440-950d-45d6-b5e7-dbea0ec93a36.png)
![image](https://user-images.githubusercontent.com/68508069/203724099-35a20dcc-86e6-4f05-b8ce-b5784d69a2a6.png)

### Mobile
![image](https://user-images.githubusercontent.com/68508069/203724645-7ccb10f8-338b-4f0f-a588-9d1da5532efa.png)
![image](https://user-images.githubusercontent.com/68508069/203724695-b942ab0c-98c3-4de7-86f3-6def67a99a04.png)

### Access Token
![image](https://user-images.githubusercontent.com/68508069/203761522-c11a8bab-e50b-44cb-8175-4eeb58018ad9.png)

2022-11-24 08:04 UTC, feliciakri requested changes

2022-11-24 08:04 UTC, feliciakri commented on pages/[lng]/products/[slug].tsx
> +      <section className={styleProducts.productsHighlight_breadcumb}>
breadcumb harusnya breadcrumb

2022-11-24 08:04 UTC, feliciakri commented on public/scss/pages/Products.module.scss
> +  &_breadcumb
ini juga breadcumb harusnya breadcrumb

2022-11-24 08:17 UTC, mayun19 commented on pages/[lng]/products/[slug].tsx
> +    SEO: { title: titleProductSection },
ini bisa "titleProductSection" aja #

2022-11-24 08:23 UTC, mayun19 commented
request ss Implement access token sekalian yah

2022-11-24 10:13 UTC, virginiaritonga approved these changes

2022-11-24 10:37 UTC, feliciakri approved these changes

2022-11-24 10:39 UTC, tiarss approved these changes

2022-11-24 10:44 UTC, mayun19 approved these changes

2022-11-25 02:17 UTC, inezamandha approved these changes

2022-11-25 02:18 UTC, inezamandha approved these changes

2022-11-25 02:18 UTC, inezamandha commented on pages/[lng]/products/[slug].tsx
> +    window.addEventListener("scroll", handleScroll);
ini yang ada titik titik komanya apakah boleh dihapus saja? biar konsisten gitu kulihat banyakan gapakai semicolon

2022-11-25 02:18 UTC, inezamandha commented on pages/[lng]/products/[slug].tsx
> +  const [currPage, setCurrPage] = useState(0);
ini juga terkait semicolon an yaah

2022-11-25 02:18 UTC, inezamandha commented on pages/[lng]/products/[slug].tsx
> +  const totalPage = Math.ceil(pageInfo.totalItems / pageInfo.itemPerPage);
ini juga hehe

2022-11-25 02:18 UTC, inezamandha commented on pages/[lng]/products/[slug].tsx
> +  });
buat ke bawah bawahnya, ku juga sama request per semi colonan ya

2022-11-25 09:11 UTC, merged