feat: revamp the order history page
sirclo-solution/template-urban pull request #90
Opened 2023-01-03 08:15 UTC by lukmannm

Dekstop:
VA:
![image](https://user-images.githubusercontent.com/60541277/210319886-b914bbe2-1058-4b34-9950-7a46fbe6c971.png)
eWallet:
![image](https://user-images.githubusercontent.com/60541277/210319979-1eca5eb7-9502-40da-8b52-2af7330969ba.png)
Manual Bank Transfer:
![image](https://user-images.githubusercontent.com/60541277/210320076-a8485bde-0346-4f46-9462-3788c60190ee.png)
Qr Code:
![image](https://user-images.githubusercontent.com/60541277/210320138-7c6c9c58-ed9f-43bf-9d3f-0cd59455045f.png)
OTC:
![image](https://user-images.githubusercontent.com/60541277/210320168-48f6efe2-5c89-4f71-88b5-51ddceed6fbd.png)

Mobile:
VA:
![image](https://user-images.githubusercontent.com/60541277/210320253-19bf5f43-d4f6-4f83-b5b7-b38283ed8b69.png)

eWallet:
![image](https://user-images.githubusercontent.com/60541277/210320267-e40b2d5b-f32f-453e-ae30-11ad3b64c446.png)

Manual Bank Transfer:
![image](https://user-images.githubusercontent.com/60541277/210320286-7e06478c-60ce-4157-848b-e779a38a379a.png)

Qr Code:
![image](https://user-images.githubusercontent.com/60541277/210320310-b870848a-25d8-47e2-8447-502dd1ba9a3a.png)

OTC:
![image](https://user-images.githubusercontent.com/60541277/210320320-f5d26238-bb31-4358-9cf9-3ed9ecb44b73.png)

Toash:
![image](https://user-images.githubusercontent.com/60541277/210320357-3aa7dbed-1d19-40ca-a6c6-986f262a877d.png)
![image](https://user-images.githubusercontent.com/60541277/210320371-cc07fd2b-b349-4ed0-bd31-ece006b9602c.png)

2023-01-03 08:29 UTC, virginiaritonga approved these changes

2023-01-03 08:29 UTC, virginiaritonga commented on locales/en/paymentMethod.ts
> +      "continuePayment": "Continue to Payment"
sort ke atas yaa

2023-01-03 08:29 UTC, virginiaritonga commented on locales/id/paymentMethod.ts
> +      "continuePayment": "Lanjutkan pembayaran"
sort ke atas yaa

2023-01-03 09:27 UTC, mayun19 requested changes

2023-01-03 09:27 UTC, mayun19 commented on pages/[lng]/account/index.tsx
> +import { CheckCircle, Copy, Download } from 'react-feather'
```
{ 
   CheckCircle, 
   Copy, 
   Download 
}
```

klo 3 variable jdiin gini

2023-01-03 09:27 UTC, mayun19 commented on public/scss/pages/Account.module.scss
> +        height: 12px;
bisa pakai mixin

2023-01-03 09:27 UTC, mayun19 commented on public/scss/pages/Account.module.scss
> +          height: 12px;
idem

2023-01-03 09:27 UTC, mayun19 commented on public/scss/pages/Account.module.scss
> +          width: 14px;
sama

2023-01-03 09:27 UTC, mayun19 commented on public/scss/pages/Account.module.scss
> +        height: 15px;
idem

2023-01-03 09:27 UTC, mayun19 commented on public/scss/pages/Account.module.scss
> +        font-weight: 400 !important;
bisa pake mixin

2023-01-03 09:27 UTC, mayun19 commented on public/scss/pages/Account.module.scss
> +        font-weight: 400 !important;
bisa pake mixin

2023-01-03 10:17 UTC, mayun19 approved these changes

2023-01-03 10:22 UTC, lukmannm commented on public/scss/pages/Account.module.scss
> +        font-weight: 400 !important;
izin resolve, seperti yang kita didiskusikan dichat

2023-01-03 10:23 UTC, lukmannm commented on public/scss/pages/Account.module.scss
> +        font-weight: 400 !important;
idem

2023-01-04 02:31 UTC, virginiaritonga approved these changes

2023-01-04 08:09 UTC, feliciakri approved these changes

2023-01-04 08:09 UTC, merged